"""
In this module we are discussing:
How to implement the POST method in Django,
to capture user input securely from forms and process it in the backend.
What is CSRF token ?
"""

# ------------------------------------------------------------------------
# 1. INTRODUCTION TO POST IN DJANGO
# ------------------------------------------------------------------------
# - When a user submits a form with method="post",
#   the data is sent in the HTTP request body (not visible in URL).
# - Django provides request.POST dictionary to access this data.
# - Unlike GET, POST is more secure and can handle large/binary data.
# - Django requires CSRF protection for POST requests → always use {% csrf_token %}.

# ------------------------------------------------------------------------
# 2. VIEW FUNCTION EXAMPLE
# ------------------------------------------------------------------------
# - A simple view to capture username and password entered by the user
#   and display the username back in the template.

from django.shortcuts import render

def post_method_example(request):
    detail = {'frmName': 'Practice POST Form'}
    if request.method == "POST":
        # Capture values from POST request body
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Process data (for demo, just return username)
        detail['message'] = f"Welcome, {username}! Your data was submitted via POST."
    else:
        detail['message'] = "Please fill out the form."

    return render(request, 'Unique_post_form.html', detail)

# ------------------------------------------------------------------------
# 3. TEMPLATE EXAMPLE (Unique_post_form.html)
# ------------------------------------------------------------------------
# - A simple form using POST method.
# - When user clicks submit, data is sent in request body.

"""
<!DOCTYPE html>
<html>
<head>
    <title>{{ frmName }}</title>
</head>
<body>
    <h2>{{ frmName }}</h2>

    <!-- POST Method Form -->
    <form action="" method="post">
        {% csrf_token %}
        <label>Username:</label>
        <input type="text" name="username">

        <label>Password:</label>
        <input type="password" name="password">

        <button type="submit">Login (POST)</button>
    </form>

    <!-- Display message -->
    <p><strong>Message:</strong> {{ message }}</p>
</body>
</html>
"""

# ------------------------------------------------------------------------
# 4. HOW IT WORKS
# ------------------------------------------------------------------------
# - User enters username and password, then clicks submit.
# - Browser sends request with data in body → not visible in URL.
# - Django view reads request.POST['username'] and request.POST['password'].
# - View processes data and passes a message back to template.
# - Template displays confirmation message dynamically.

# ------------------------------------------------------------------------
# 5. BEST PRACTICES
# ------------------------------------------------------------------------
# - Always include {% csrf_token %} in POST forms → prevents CSRF attacks.
# - Validate and sanitize user input before saving to database.
# - Use POST for sensitive data (login, signup, payments).
# - Do not expose passwords or confidential info in GET requests.
# - Keep logic in views, presentation in templates.
# ------------------------------------------------------------------------

# ---------------------------------------------------------------------------------------------
# 💫💫💫💫💫💫💫💫💫💫 NOTE  💫💫💫💫💫💫💫💫💫💫 VVI 💫💫💫💫💫💫💫💫💫💫 VVI # --------
# ---------------------------------------------------------------------------------------------
"""
🔹 What is CSRF Token?
- CSRF stands for Cross-Site Request Forgery.
- It’s a type of attack where a malicious site tricks a logged-in user into submitting a request to your site without their knowledge.
- Example: If you’re logged into your bank, a hacker could trick your browser into sending a fake transfer request.

🔹 Why CSRF Token is Needed in Django
- Django protects against CSRF attacks by requiring a unique token in every POST form.
- This token is generated by Django and checked when the form is submitted.
- If the token is missing or invalid, Django will reject the request with a 403 Forbidden error.

🔹 How to Use CSRF Token in Templates Inside your POST form, always include:

<form action="/login" method="post">
    {% csrf_token %}
    <label>Username:</label>
    <input type="text" name="username">

    <label>Password:</label>
    <input type="password" name="password">

    <button type="submit">Login (POST)</button>
</form>

"""